name: pack_test
version: '1.0.0'

profile: pack_test

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  pack_test:
    staging:
      +materialized: view
    dimension:
      +materialized: table
    facts:
      +materialized: table
    marts:
      +materialized: table

tests:
  +store_failures: true
